<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../.resources/report.css" type="text/css"/><link rel="shortcut icon" href="../.resources/report.gif" type="image/gif"/><title>CertPathValidatorException.java</title><link rel="stylesheet" href="../.resources/prettify.css" type="text/css"/><script type="text/javascript" src="../.resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="right"><a href="../.sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">Foo</a> &gt; <a href="index.html" class="el_package">java.security.cert</a> &gt; <span class="el_source">CertPathValidatorException.java</span></div><h1>CertPathValidatorException.java</h1><pre class="source lang-java linenums">/*
 * Copyright (c) 2000, 2013, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the &quot;Classpath&quot; exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package java.security.cert;

import java.io.InvalidObjectException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.security.GeneralSecurityException;

/**
 * An exception indicating one of a variety of problems encountered when
 * validating a certification path.
 * &lt;p&gt;
 * A {@code CertPathValidatorException} provides support for wrapping
 * exceptions. The {@link #getCause getCause} method returns the throwable,
 * if any, that caused this exception to be thrown.
 * &lt;p&gt;
 * A {@code CertPathValidatorException} may also include the
 * certification path that was being validated when the exception was thrown,
 * the index of the certificate in the certification path that caused the
 * exception to be thrown, and the reason that caused the failure. Use the
 * {@link #getCertPath getCertPath}, {@link #getIndex getIndex}, and
 * {@link #getReason getReason} methods to retrieve this information.
 *
 * &lt;p&gt;
 * &lt;b&gt;Concurrent Access&lt;/b&gt;
 * &lt;p&gt;
 * Unless otherwise specified, the methods defined in this class are not
 * thread-safe. Multiple threads that need to access a single
 * object concurrently should synchronize amongst themselves and
 * provide the necessary locking. Multiple threads each manipulating
 * separate objects need not synchronize.
 *
 * @see CertPathValidator
 *
 * @since       1.4
 * @author      Yassir Elley
 */
public class CertPathValidatorException extends GeneralSecurityException {

    private static final long serialVersionUID = -3083180014971893139L;

    /**
     * @serial the index of the certificate in the certification path
     * that caused the exception to be thrown
     */
<span class="fc" id="L70">    private int index = -1;</span>

    /**
     * @serial the {@code CertPath} that was being validated when
     * the exception was thrown
     */
    private CertPath certPath;

    /**
     * @serial the reason the validation failed
     */
<span class="fc" id="L81">    private Reason reason = BasicReason.UNSPECIFIED;</span>

    /**
     * Creates a {@code CertPathValidatorException} with
     * no detail message.
     */
    public CertPathValidatorException() {
<span class="nc" id="L88">        this(null, null);</span>
<span class="nc" id="L89">    }</span>

    /**
     * Creates a {@code CertPathValidatorException} with the given
     * detail message. A detail message is a {@code String} that
     * describes this particular exception.
     *
     * @param msg the detail message
     */
    public CertPathValidatorException(String msg) {
<span class="fc" id="L99">        this(msg, null);</span>
<span class="fc" id="L100">    }</span>

    /**
     * Creates a {@code CertPathValidatorException} that wraps the
     * specified throwable. This allows any exception to be converted into a
     * {@code CertPathValidatorException}, while retaining information
     * about the wrapped exception, which may be useful for debugging. The
     * detail message is set to ({@code cause==null ? null : cause.toString()})
     * (which typically contains the class and detail message of
     * cause).
     *
     * @param cause the cause (which is saved for later retrieval by the
     * {@link #getCause getCause()} method). (A {@code null} value is
     * permitted, and indicates that the cause is nonexistent or unknown.)
     */
    public CertPathValidatorException(Throwable cause) {
<span class="nc bnc" id="L116" title="All 2 branches missed.">        this((cause == null ? null : cause.toString()), cause);</span>
<span class="nc" id="L117">    }</span>

    /**
     * Creates a {@code CertPathValidatorException} with the specified
     * detail message and cause.
     *
     * @param msg the detail message
     * @param cause the cause (which is saved for later retrieval by the
     * {@link #getCause getCause()} method). (A {@code null} value is
     * permitted, and indicates that the cause is nonexistent or unknown.)
     */
    public CertPathValidatorException(String msg, Throwable cause) {
<span class="fc" id="L129">        this(msg, cause, null, -1);</span>
<span class="fc" id="L130">    }</span>

    /**
     * Creates a {@code CertPathValidatorException} with the specified
     * detail message, cause, certification path, and index.
     *
     * @param msg the detail message (or {@code null} if none)
     * @param cause the cause (or {@code null} if none)
     * @param certPath the certification path that was in the process of
     * being validated when the error was encountered
     * @param index the index of the certificate in the certification path
     * that caused the error (or -1 if not applicable). Note that
     * the list of certificates in a {@code CertPath} is zero based.
     * @throws IndexOutOfBoundsException if the index is out of range
     * {@code (index &lt; -1 || (certPath != null &amp;&amp; index &gt;=
     * certPath.getCertificates().size()) }
     * @throws IllegalArgumentException if {@code certPath} is
     * {@code null} and {@code index} is not -1
     */
    public CertPathValidatorException(String msg, Throwable cause,
            CertPath certPath, int index) {
<span class="fc" id="L151">        this(msg, cause, certPath, index, BasicReason.UNSPECIFIED);</span>
<span class="fc" id="L152">    }</span>

    /**
     * Creates a {@code CertPathValidatorException} with the specified
     * detail message, cause, certification path, index, and reason.
     *
     * @param msg the detail message (or {@code null} if none)
     * @param cause the cause (or {@code null} if none)
     * @param certPath the certification path that was in the process of
     * being validated when the error was encountered
     * @param index the index of the certificate in the certification path
     * that caused the error (or -1 if not applicable). Note that
     * the list of certificates in a {@code CertPath} is zero based.
     * @param reason the reason the validation failed
     * @throws IndexOutOfBoundsException if the index is out of range
     * {@code (index &lt; -1 || (certPath != null &amp;&amp; index &gt;=
     * certPath.getCertificates().size()) }
     * @throws IllegalArgumentException if {@code certPath} is
     * {@code null} and {@code index} is not -1
     * @throws NullPointerException if {@code reason} is {@code null}
     *
     * @since 1.7
     */
    public CertPathValidatorException(String msg, Throwable cause,
            CertPath certPath, int index, Reason reason) {
<span class="fc" id="L177">        super(msg, cause);</span>
<span class="pc bpc" id="L178" title="1 of 4 branches missed.">        if (certPath == null &amp;&amp; index != -1) {</span>
<span class="nc" id="L179">            throw new IllegalArgumentException();</span>
        }
<span class="pc bpc" id="L181" title="1 of 4 branches missed.">        if (index &lt; -1 ||</span>
<span class="pc bpc" id="L182" title="1 of 2 branches missed.">            (certPath != null &amp;&amp; index &gt;= certPath.getCertificates().size())) {</span>
<span class="nc" id="L183">            throw new IndexOutOfBoundsException();</span>
        }
<span class="pc bpc" id="L185" title="1 of 2 branches missed.">        if (reason == null) {</span>
<span class="nc" id="L186">            throw new NullPointerException(&quot;reason can't be null&quot;);</span>
        }
<span class="fc" id="L188">        this.certPath = certPath;</span>
<span class="fc" id="L189">        this.index = index;</span>
<span class="fc" id="L190">        this.reason = reason;</span>
<span class="fc" id="L191">    }</span>

    /**
     * Returns the certification path that was being validated when
     * the exception was thrown.
     *
     * @return the {@code CertPath} that was being validated when
     * the exception was thrown (or {@code null} if not specified)
     */
    public CertPath getCertPath() {
<span class="nc" id="L201">        return this.certPath;</span>
    }

    /**
     * Returns the index of the certificate in the certification path
     * that caused the exception to be thrown. Note that the list of
     * certificates in a {@code CertPath} is zero based. If no
     * index has been set, -1 is returned.
     *
     * @return the index that has been set, or -1 if none has been set
     */
    public int getIndex() {
<span class="nc" id="L213">        return this.index;</span>
    }

    /**
     * Returns the reason that the validation failed. The reason is
     * associated with the index of the certificate returned by
     * {@link #getIndex}.
     *
     * @return the reason that the validation failed, or
     *    {@code BasicReason.UNSPECIFIED} if a reason has not been
     *    specified
     *
     * @since 1.7
     */
    public Reason getReason() {
<span class="fc" id="L228">        return this.reason;</span>
    }

    private void readObject(ObjectInputStream stream)
        throws ClassNotFoundException, IOException {
<span class="nc" id="L233">        stream.defaultReadObject();</span>
<span class="nc bnc" id="L234" title="All 2 branches missed.">        if (reason == null) {</span>
<span class="nc" id="L235">            reason = BasicReason.UNSPECIFIED;</span>
        }
<span class="nc bnc" id="L237" title="All 4 branches missed.">        if (certPath == null &amp;&amp; index != -1) {</span>
<span class="nc" id="L238">            throw new InvalidObjectException(&quot;certpath is null and index != -1&quot;);</span>
        }
<span class="nc bnc" id="L240" title="All 4 branches missed.">        if (index &lt; -1 ||</span>
<span class="nc bnc" id="L241" title="All 2 branches missed.">            (certPath != null &amp;&amp; index &gt;= certPath.getCertificates().size())) {</span>
<span class="nc" id="L242">            throw new InvalidObjectException(&quot;index out of range&quot;);</span>
        }
<span class="nc" id="L244">    }</span>

    /**
     * The reason the validation algorithm failed.
     *
     * @since 1.7
     */
    public static interface Reason extends java.io.Serializable { }


    /**
     * The BasicReason enumerates the potential reasons that a certification
     * path of any type may be invalid.
     *
     * @since 1.7
     */
<span class="pc" id="L260">    public static enum BasicReason implements Reason {</span>
        /**
         * Unspecified reason.
         */
<span class="fc" id="L264">        UNSPECIFIED,</span>

        /**
         * The certificate is expired.
         */
<span class="fc" id="L269">        EXPIRED,</span>

        /**
         * The certificate is not yet valid.
         */
<span class="fc" id="L274">        NOT_YET_VALID,</span>

        /**
         * The certificate is revoked.
         */
<span class="fc" id="L279">        REVOKED,</span>

        /**
         * The revocation status of the certificate could not be determined.
         */
<span class="fc" id="L284">        UNDETERMINED_REVOCATION_STATUS,</span>

        /**
         * The signature is invalid.
         */
<span class="fc" id="L289">        INVALID_SIGNATURE,</span>

        /**
         * The public key or the signature algorithm has been constrained.
         */
<span class="fc" id="L294">        ALGORITHM_CONSTRAINED</span>
    }
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.eclemma.org/jacoco">JaCoCo</a> 0.6.4.201312031056</span></div></body></html>